version: 2.1

orbs:
  gradle: circleci/gradle@2.2

jobs:
  build-and-test:
    docker:
      - image: circleci/android:api-28
    steps:
      # Checkout the code as the first step.
      # Next attempt to restore the dependencies that have been cached.
      # If they restore, great! The next step to install them should execute quickly.
      # If not, the step will download them again.
      # Then run your tests!
      # CircleCI will report the results back to your VCS provider.
      - checkout
      - gradle/with_cache:
          steps:
            - run:
                name: Download Dependencies
                command: ./gradlew androidDependencies
            - run:
                name: Run Tests
                command: ./gradlew lint test


workflows:
  main:
    jobs:
      - build-and-test
